/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package texttospeech;

import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Kadek
 * GUI for the application
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        StyledDocument doc = textPane.getStyledDocument();
        SimpleAttributeSet left = new SimpleAttributeSet();
        StyleConstants.setAlignment(left, StyleConstants.ALIGN_LEFT);
        doc.setParagraphAttributes(0, doc.getLength(), left, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGlass2 = new usu.widget.glass.PanelGlass();
        label1 = new usu.widget.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextPane();
        speakButton = new usu.widget.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Malay Speech Synthesizer");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(768, 480));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelGlass2.setAlpha(1.0F);
        panelGlass2.setBackground(new java.awt.Color(255, 255, 255));
        panelGlass2.setForeground(new java.awt.Color(255, 255, 255));
        panelGlass2.setMaximumSize(new java.awt.Dimension(768, 480));
        panelGlass2.setMinimumSize(new java.awt.Dimension(768, 480));
        panelGlass2.setPreferredSize(new java.awt.Dimension(768, 480));
        panelGlass2.setRound(false);
        panelGlass2.setWarna(new java.awt.Color(55, 136, 234));

        label1.setBackground(new java.awt.Color(13, 38, 177));
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("Malay Speech Synthesizer");
        label1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        label1.setOpaque(true);

        jScrollPane2.setMaximumSize(new java.awt.Dimension(512, 308));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(512, 308));

        textPane.setBackground(new java.awt.Color(229, 234, 242));
        textPane.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textPane.setMaximumSize(new java.awt.Dimension(512, 308));
        textPane.setMinimumSize(new java.awt.Dimension(512, 308));
        textPane.setPreferredSize(new java.awt.Dimension(512, 308));
        jScrollPane2.setViewportView(textPane);

        speakButton.setBackground(new java.awt.Color(16, 46, 206));
        speakButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        speakButton.setForeground(new java.awt.Color(255, 255, 255));
        speakButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        speakButton.setText("SPEAK IT!");
        speakButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        speakButton.setOpaque(true);
        speakButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                speakButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panelGlass2Layout = new javax.swing.GroupLayout(panelGlass2);
        panelGlass2.setLayout(panelGlass2Layout);
        panelGlass2Layout.setHorizontalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelGlass2Layout.createSequentialGroup()
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGlass2Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(speakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        panelGlass2Layout.setVerticalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass2Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(speakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(panelGlass2, new java.awt.GridBagConstraints());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void speakButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_speakButtonMouseReleased
        // TODO add your handling code here:
        String text = textPane.getText();

        if (text.isEmpty()) {
            showMessageDialog(null, "Text is empty!");
            //showMessageDialog(null, System.getProperty("user.dir"));
        } else {
            speakButton.setEnabled(false);
            new SwingWorker<Void, Void>() {
                @Override
                protected Void doInBackground() {
                    String outputName = new Preprocessing(text).getOutputName();
                    System.out.println(outputName);

                    new AudioPlayer(ConstantObjects.OUTPUTFOLDER + outputName + ConstantObjects.FILEFORMAT);

                    new OutputFolderCleaner();
                    return null;
                }

                @Override
                protected void done() {
                    speakButton.setEnabled(true);
                }

            }.execute();
        }
    }//GEN-LAST:event_speakButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private usu.widget.Label label1;
    private usu.widget.glass.PanelGlass panelGlass2;
    private usu.widget.Label speakButton;
    private javax.swing.JTextPane textPane;
    // End of variables declaration//GEN-END:variables
}
